#!/usr/bin/env bash
# FizzBuzz challenge script
for ((i=1; i<=100; i++)); do
	if [ $((i%3)) -eq 0 ] && [ $((i%5)) -eq 0 ]; then
		echo "FizzBuzz"
		continue
	elif [ $((i%3)) -eq 0 ]; then
		echo "Fizz"
		continue
	elif [ $((i%5)) -eq 0 ]; then
		echo "Buzz"
		continue
	else
		echo "$i"
	fi
done
