#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd in a specified manner
while read -r line; do
	username=$(echo "$line" | cut -d ":" -f 1)
	user_id=$(echo "$line" | cut -d ":" -f 3)
	dir=$(echo "$line" | cut -d ":" -f 6)
	echo "$username:$user_id:$dir"
done < /etc/passwd	
