#!/usr/bin/env bash
# Prints hour 1 - 12 with minutes
hour=0
min=1
while [ $hour -lt 13 ]; do
	echo "Hour: $hour"
	while [ $min -lt 60 ]; do
		echo "$min"
		((min++))
	done
	if [ $min -eq 60 ]; then
		min=1
	fi
	((hour++))
done
